- contracts/Configurator.sol
As proposed by OpenZeppelin, since `governor` is mutable in configuration. For correctness, we should either do this or update docs that `baseToken` and `trackingIndexScale` are technically mutable. If we check for `governor`, then governance could reset `governor` to `address(0)` and then overwrite the entire config, which would include `baseToken` and `trackingIndexScale`.
> Configurator check for baseToken instead of governor

- contracts/Comet.sol
- test/supply-test.ts
- test/withdraw-test.ts
This PR fixes a math overflow bug that occasionally occurs when supplying 0 base. I also added a unit test to verify the fix, as well as another unit test to show a weird quirk that can occur when withdrawing 0 base. 
**Bug details:**
In `supplyBase`, we calculate `dstPrincipalNew` using `dstPrincipal` (old principal value before amount is supplied). The formula is:
`int104 dstPrincipalNew = principalValue(presentValue(dstPrincipal) + signed104(amount))`
When `amount=0`, the formula condenses to:
`dstPrincipalNew = principalValue(presentValue(dstPrincipal))`
Due to the fact that both `principalValue` and `presentValue` round down in favor of the protocol, we can actually end up with a value of `dstPrincipalNew < dstPrincipal`. 
This breaks our assumption in `repayAndSupplyAmount` that …
> Fix overflow bug that occasionally occurs when supplying 0 base

- contracts/Comet.sol
- contracts/CometCore.sol
- contracts/CometMainInterface.sol
This internally uses 256 bits for present values instead of artificially constraining them to 104 bits. This avoids an unsafe cast we were doing previously to save gas, and also opens up some other gas optimizations / contract size reductions. However, this also removes some previously unchecked math, which makes it a slight tradeoff in terms of gas.
> Represent present value with 256 bits instead of 104

- deployments/fuji/migrations/1644432723_deploy_fuji.ts
- deployments/kovan/migrations/1644388553_deploy_kovan.ts
- scenario/constraints/ModernConstraint.ts
- scenario/utils.ts
- src/deploy/Development.ts
- src/deploy/Network.ts
- src/deploy/index.ts
- src/utils.ts
This PR improves our deployment scripts in a few ways:
- Consolidate all deployment options into `DeployCometOptionalParams` so only a single object for optional params needs to be passed into `deployComet`
- Introduce a new `ContractsToDeploy` optional param that allows for more specificity in which contracts to deploy. This should put us in the right direction for mainnet and L2 migrations that don't need certain contracts (e.g. `SimpleTimelock` and `GovernorSimple`)
`ContractsToDeploy` usage:
If `ContractsToDeploy` is not provided as an optional param, all contracts will be deployed. The interface also has an `all` property that explicitly states to deploy all contracts. The `all` property can be combined with other properties to deploy "all but some" contracts. e.g.
```
{ all: true, …
```
> Support deploying specific contracts instead of all at once

- package.json
The main Liquidation Bot command has mainnet hard-coded as an argument.
Removing so that users can run it against testnet (to get those sweet testnet profits).
> remove hard-coded network argument

- deployments/kovan/migrations/1644388553_deploy_kovan.ts
- plugins/deployment_manager/Deploy.ts
- plugins/deployment_manager/DeploymentManager.ts
- plugins/deployment_manager/Utils.ts
- src/deploy/Network.ts
This PR makes our deploys more consistent by handling network failures using retries and timeouts (to handle hanging txns). A new function `asyncCallWithRetry` is added to the `DeploymentManager` for this purpose.
I opted to implement the retry/timeout logic at the function level. The other approach would be to wrap an entire deployment script around one retry/timeout handler, but this requires us to cache which txns were already executed, which is difficult to generically do. The trade-off with my approach is that we have to explicitly wrap ad hoc (non-deploy) txns such as `usdc.initialize()` with an `asyncCallWithRetry` function in the deployment script.
> Fault tolerant deploys

- scenario/AllowBySigScenario.ts
- scenario/AllowScenario.ts
- scenario/ApproveThisScenario.ts
- scenario/CometScenario.ts
- scenario/ConfiguratorScenario.ts
- scenario/ConstraintScenario.ts
- scenario/InterestRateScenario.ts
- scenario/LiquidationScenario.ts
- scenario/PauseGuardianScenario.ts
- scenario/SupplyScenario.ts
- scenario/TransferScenario.ts
- scenario/WithdrawReservesScenario.ts
- scenario/WithdrawScenario.ts
This PR removes unnecessary usages of `upgrade: true` from our scenarios. Some scenarios still have valid reasons for using it (e.g. interest rate scenarios that use it to upgrade the interest rate params), so these are not fully removed from all scenarios.
> Remove all unnecessary usages of `upgrade: true` in scenarios

- .github/workflows/deploy-market.yaml
- .github/workflows/run-scenarios.yaml
- README.md
- deployments/fuji/deploy.ts
- deployments/fuji/migrations/1653512197_seed_rewards_with_comp.ts
- deployments/kovan/deploy.ts
- deployments/kovan/migrations/1653512186_seed_rewards_with_comp.ts
- hardhat.config.ts
- plugins/deployment_manager/Migration.ts
- plugins/deployment_manager/MigrationTemplate.ts
- plugins/deployment_manager/test/DeploymentManagerTest.ts
- plugins/deployment_manager/test/MigrationTemplateTest.ts
- plugins/deployment_manager/test/MigrationTest.ts
- plugins/deployment_manager/test/migration.ts
- scenario/CometScenario.ts
- scenario/constraints/MigrationConstraint.ts
- scenario/constraints/ProposalConstraint.ts
- scenario/constraints/index.ts
- scenario/context/CometContext.ts
- scenario/utils.ts
- tasks/deployment_manager/task.ts
We are working towards a simplified/standard workflow which we still need to document:
1. Open a PR with a migration script
2. Run 'prepare' workflow in GitHub CI
- this should deploy any necessary contracts
- changes to roots should auto-commit to the PR branch
- maybe go post in the forum about it for review
3. Run 'enact' workflow in GitHub CI or elsewhere
- this should make any necessary gov proposals
4. Once the proposal is accepted by gov, merge PR with new roots
NB: currently `roots.json` changes *can* happen in migrations. In the next iteration of this, we will have a separate workflow for the (single) 'deploy' script, which should be the only thing modifying roots. Changes which happen in migrations should be automatically spidered in when any related proposal passes. Otherwise, …
> Taming migration scripts

- scenario/ApproveThisScenario.ts
- scenario/ConfiguratorScenario.ts
- scenario/GovernanceScenario.ts
- scenario/PauseGuardianScenario.ts
- scenario/WithdrawReservesScenario.ts
- scenario/constraints/MigrationConstraint.ts
- scenario/constraints/PauseConstraint.ts
- scenario/context/CometActor.ts
- scenario/context/CometContext.ts
- scenario/utils.ts
Right now, scenarios set the admin signer to be the address returned by `governor.admins(0)`. This works on testnets where the governor contract is `GovernorSimple`. However, this wouldn't for mainnet because `GovernorBravo` doesn't have an `admins` list to read from. 
This PR fixes the issue by setting the admin signer to be `comet.governor()`, which could either be an EOA or a contract address (`Timelock`), and using it to directly sign txns for contract upgrades. Since the admin could be a contract address, we have to set the next block's base fee to 0 and set the gas price to 0 whenever sending a txn with it.
> Fix scenario admin issue for chains without GovernorSimple

- hardhat.config.ts
This should be the real fix rather than #499, which inconsistently specifies `ETH_PK` in different contexts .
> With ETH_PK we need to generate multiple accounts for unit tests

- contracts/test/IGovernorBravo.sol
- deployments/mainnet/configuration.json
- deployments/mainnet/deploy.ts
- hardhat.config.ts
- package.json
- plugins/deployment_manager/DeploymentManager.ts
- plugins/scenario/World.ts
- plugins/scenario/utils/TokenSourcer.ts
- plugins/scenario/utils/hreForBase.ts
- scenario/AllowBySigScenario.ts
- scenario/ConstraintScenario.ts
- scenario/GovernanceScenario.ts
- scenario/SupplyScenario.ts
- scenario/WithdrawReservesScenario.ts
- scenario/WithdrawScenario.ts
- scenario/constraints/MigrationConstraint.ts
- scenario/context/CometContext.ts
- scenario/utils.ts
- src/deploy/Network.ts
- src/deploy/NetworkConfiguration.ts
- yarn.lock
This PR introduces mainnet deploy scripts and allows us to fully test hypothetical deployments of Comet using scenarios without having to first deploy the contracts on-chain. This is useful for our mainnet launch, where we want to test a hypothetical mainnet deployment before actually deploying. 
A few big changes in this PR:
- Adding a new deployment script and `configuration.json` for `mainnet` that allows us to test it using scenarios
- Supporting mainnet governance scenarios by having `fastExecuteGovernance` work for deployments with a real `Timelock` that require votes to pass proposals
- Allowing the `configuration.json` file to specify an optional `address` field for the base asset and each collateral asset. This is useful for chains that already have pre-existing tokens we want to …
> Mainnet deploy script and scenarios

- plugins/deployment_manager/DeploymentManager.ts
Adding this back since it is needed for retrying hanging txns and was removed previously when we mistakenly thought it contributed to the nonce re-use issues in scenarios.
> Add back signer reset

- contracts/liquidator/Liquidator.sol
- test/liquidation/liquidation-bot-test.ts
- test/liquidation/makeLiquidatableProtocol.ts
adding an immutable recipient address to the Liquidator contract. when you deploy, you specify the address that should receive the profits of any liquidations.
this should prevent generalized front-runners from taking profitable transactions from the caller of the Liquidator contract, since a front-runner that mimicked the arguments would only end up sending profits to the specified address.
it has the added benefit of allowing us to initiate transactions from a hot wallet but automatically transfer liquidated funds to a cold wallet.
cc: @ajb413
> add recipient to Liquidator.sol

- .github/workflows/deploy-market.yaml
- .github/workflows/enact-migration.yaml
- .github/workflows/prepare-migration.yaml
This patch adds Seacrest to our GitHub Actions for Deploy, Prepare and Enact. As per [Seacrest](https://github.com/hayesgm/seacrest), when you run these actions, you will be prompted with a QR Code to connect WalletConnect. Once you scan that QR code (with, e.g. MetaMask Mobile), the rest of the code will depend on that account for any transactions (e.g. deploying a contract). You will individually sign off on any requests during the progression of the action without any risk of key exfiltration.
Note: this patch removes `eth_pk` as an option, but technically we could have this as an either/or. I just tend to think it's superior enough that we should supplant the old flow.
> Add Seacrest Support

- deployments/fuji/usdc/configuration.json
- deployments/hardhat/dai/configuration.json
- deployments/kovan/usdc/configuration.json
- deployments/mainnet/usdc/configuration.json
- scenario/context/CometContext.ts
- src/deploy/Network.ts
- src/deploy/NetworkConfiguration.ts
- src/deploy/index.ts
This PR updates the deploy function to set the `RewardConfig` in the `CometRewards` contract as part of the deployment process. 
Two optional fields have been added to `configuration.json` to specify the reward token for a certain deployment: `rewardToken` (token symbol) and `rewardTokenAddress`. If the rewards contract is to be deployed, then one of these two fields must be specified in the deployment's `configuration.json`.
> Set RewardConfig during initial deployment

- scenario/constraints/ProposalConstraint.ts
This bug is causing all our mainnet scenarios to run with 0 solutions (basically mainnet scenarios are skipped).
> Fix empty solutions being returned by proposal constraint

- .github/workflows/run-scenarios.yaml
- .gitignore
- .prettierignore
- plugins/deployment_manager/ContractMap.ts
- plugins/deployment_manager/Deploy.ts
- plugins/deployment_manager/DeploymentManager.ts
- plugins/deployment_manager/Import.ts
- plugins/deployment_manager/Spider.ts
- plugins/deployment_manager/test/ContractMapTest.ts
- plugins/deployment_manager/test/DeployHelpers.ts
- plugins/deployment_manager/test/DeployTest.ts
- plugins/deployment_manager/test/DeploymentManagerTest.ts
- plugins/deployment_manager/test/ImportTest.ts
- plugins/deployment_manager/test/SpiderTest.ts
- plugins/deployment_manager/test/VerifyArgsTest.ts
- plugins/deployment_manager/test/VerifyTest.ts
- tasks/deployment_manager/task.ts
- tasks/spider/task.ts
I was wrong to think contract addresses are always a function of bytecode.
This adds caching per network the right way, being aware of the (true) network we are cloning from or deploying to.
This was a bit easier to add with proxies out of the way.
> Make contracts cached per network properly

- contracts/Configurator.sol
- scenario/context/CometContext.ts
- src/deploy/index.ts
This makes a contract change to configurator, to make `getAssetIndex` public.
It was useful to be able to call this directly when trying to debug these  issues and I think it ought to be public.
Somehow the upgrade path in bumpSupplyCaps was completely broken and had never been used (at least since adding the per-market configuration).
This fixes the call to updateSupplyCap and bypasses governance for this constraint helper to speed it up.
Also remove some whales, since we are voting with all of them and its unnecessary.
> Make getAssetIndex public, fix bumpSupplyCaps

- scenario/RewardsScenario.ts
- scenario/constraints/CometBalanceConstraint.ts
- scenario/constraints/UtilizationConstraint.ts
- scenario/context/CometActor.ts
- scenario/context/CometContext.ts
We often get the bumping wrong, as in the case of borrowing.
This also makes bumping slightly more efficient and correct, since it doesn't allow arbitrary unknown assets, but just ignores the case of base token.
With this, mainnet scenarios pass even without the proposal!
> Add a `safeSupplyAsset` instead of bumping everywhere first

- deployments/fuji/usdc/deploy.ts
- deployments/hardhat/dai/deploy.ts
- deployments/kovan/usdc/deploy.ts
- plugins/deployment_manager/Deploy.ts
- plugins/deployment_manager/DeploymentManager.ts
- plugins/deployment_manager/Spider.ts
- plugins/deployment_manager/Types.ts
- plugins/deployment_manager/Utils.ts
- plugins/deployment_manager/test/VerifyArgsTest.ts
- plugins/scenario/worker/Worker.ts
- src/deploy/Network.ts
- tasks/deployment_manager/task.ts
This replaces debug calls with calls to a tracer from the DeploymentManager.
The trace function makes logging more consistent with network names and transaction response support, which allows us to capture a detailed spend history and report it on the cli.
> Add tracer to DeploymentManager to capture spend and improve logging

- hardhat.config.ts
These changes were accidentally dropped when merging Seacrest.
> Fix Seacrest Support

- contracts/Bulker.sol
- deployments/kovan/usdc/deploy.ts
- deployments/mainnet/usdc/deploy.ts
- test/bulker-test.ts
- test/helpers.ts
This PR updates Bulker to no longer constantize the Comet and reward contract addresses. Instead, these addresses are passed in as calldata in the `invoke` function. This allows one Bulker contract to generically work across different Comet deployments and reward contracts.
> Generic Bulker

- scenario/SupplyScenario.ts
- scenario/TransferScenario.ts
- scenario/WithdrawScenario.ts
- scenario/constraints/FilterConstraint.ts
- scenario/constraints/Requirements.ts
- scenario/constraints/index.ts
- scenario/context/CometContext.ts
- scenario/utils.ts
This PR increases the coverage of our supply/transfer/withdraw scenarios to all collateral assets (instead of just the first one). 
I also added a FilterConstraint to filter out solutions early on, before any other constraints that could revert are run.
> Run scenarios for all collateral assets; Introduce FilterConstraint

- plugins/deployment_manager/NonceManager.ts
- scenario/context/CometContext.ts
If there's an error sending a transaction we want to reset the nonce.
This sneakily intercepts errors and resets in our NonceManager subclass.
> Intercept sendTransaction in NonceManager to reset pending counts

- contracts/IGovernorBravo.sol
- plugins/scenario/utils/TokenSourcer.ts
- scenario/constraints/ProposalConstraint.ts
- scenario/context/CometContext.ts
- scenario/context/Gov.ts
- scenario/utils.ts
Scen plugin should not depend on scens.
Errors should be thrown in fetchQuery to avoid misusage.
All open proposals should be executed, not just pending/active.
This increases the need for 'static constraints' as proposal constraint is very expensive.
This also hacks in a constant for timelock buf which should really be computed.
> Fix proposal constraint and fetchQuery

- scenario/context/CometContext.ts
This should fix the `Timestamp X is lower than or equal to previous block's timestamp Y` errors when running `executeOpenProposal`. Scenarios on goerli are now failing for other reasons (a set of passed proposals with wrong inputs that fail when being executed).
> Fix scenario timestamp issue

- scenario/context/CometContext.ts
- src/deploy/Network.ts
- src/deploy/index.ts
For prior testnets, we completely controlled the COMP allocation, so we were able to delegate to the top mainnet whale when cloning gov. For new goerli, we are leveraging an existing gov installation, so we need to know about some external COMP whales. The current mechanism is sort of a compromise to keep complexity down and prevent scens from being even slower. We shouldn't necessarily need any sets of whales beyond 'mainnet' and 'testnet'.
> Separate whales for testnet

- plugins/deployment_manager/MigrationTemplate.ts
- plugins/deployment_manager/test/MigrationTemplateTest.ts
- plugins/scenario/utils/hreForBase.ts
- tasks/deployment_manager/task.ts
Updating the migration flow to reflect the changes for L2s/bridged chains.
In migrations, the `prepare` step will receive a `deploymentManager` for the current chain.
The `enact` step will receive a `governanceDeploymentManager` for the governing chain (most likely the mainnet deployment or the Goerli deployment).
Requires extending `hreForBase` to return non-forked HREs (the current implementation assumes that the HRE you're constructing should be a fork).
The migration task determines whether a given deployment is a bridged deployment using the `scenario.bases` config, which is somewhat strange but is currently the only place that we store whether a given deployment is governed by a different chain.
> Cross-chain migrations

- .github/workflows/enact-migration.yaml
- plugins/deployment_manager/Enacted.ts
- plugins/deployment_manager/Migration.ts
- plugins/deployment_manager/test/EnactedTest.ts
- scenario/constraints/MigrationConstraint.ts
- tasks/deployment_manager/task.ts
This PR adds back an optional `enacted` step in our migrations and programmatically sets it whenever a migration is run with `enact` on. We are bringing `enacted` back so we have a way to prevent scenarios from running the same migration again once it has already been enacted on-chain.
Example commits of GHA adding `enacted` after running a migration:
https://github.com/compound-finance/comet/pull/566/commits/04aab559697102d09d580fb688bfa6012cc13555
https://github.com/compound-finance/comet/pull/566/commits/16b3daf885609aae3ff48c604941408315500153
> Add back `enacted` step and programmatically set it after running migrations

- .github/workflows/run-scenarios.yaml
This means that one matrix job failing will no longer cancel all the other running matrix jobs.
> Disable fail-fast in matrix configuration

- yarn.lock
So we can get patch: https://github.com/compound-finance/hardhat-cover/commit/c9064e8bf04d3ae34773adbfee70cade741078ec
> pull hardhat-cover from master branch

- plugins/import/import.ts
I posted some of this in Discord; adding here for posterity.
Currently, when we want to grab Contract Creation code, we attempt to scrape the content directly from Etherscan.
We make a request for the page data at `https://etherscan.io/address/0x2260fac5e5542a773aa44fbcfedf7c193bc2c599#code`, for example, and search for the contents of a div with a particular ID.
Recently, Polygonscan put a Cloudflare challenge page in front of their pages, so our attempts to scrape their pages fail with a 503 and some page content that includes the text `polygonscan.com needs to review the security of your connection before proceeding`. This breaks our scenarios/deploys for Mumbai/Polygon.
Sometimes, the Contract Creation code can be pulled via the Etherscan API. For example, the "input" data for the …
> additional strategy for pulling Contract Creation code

- .github/workflows/run-coverage.yaml
- hardhat.config.ts
`--max-old-space-size=4096` fixes the max heap errors:
https://github.com/compound-finance/comet/actions/runs/3116058799/jobs/5053854291
bumping the Mocha timeout prevents failing for timeouts:
https://github.com/compound-finance/comet/actions/runs/3116323528/jobs/5078730536
> Fix coverage

- scenario/constraints/UtilizationConstraint.ts
Some of the scenarios that use the UtilizationConstraint are failing for `mainnet` because they're unable to source a sufficient amount of `$asset0` (in this, COMP) in order to hit the required utilization:
```
[mainnet] ... ran Comet#withdraw reverts if borrow is less than minimum borrow on 2 solutions
[mainnet] ❌ Comet#interestRate > above kink rates using hypothetical configuration constants [1 run]: Error Error: No events found within 40000 blocks for 0xc00e94Cb662C3520282E6f5717214004A7f26888
at fetchQuery (/home/runner/work/comet/comet/plugins/scenario/utils/TokenSourcer.ts:27:11)
at addTokens (/home/runner/work/comet/comet/plugins/scenario/utils/TokenSourcer.ts:108:43)
at addTokens (/home/runner/work/comet/comet/plugins/scenario/utils/TokenSourcer.ts:133:11)
``` …
> UtilizationConstraint; attempt to source from multiple assets

- contracts/IWstETH.sol
- contracts/bulkers/BaseBulker.sol
- contracts/bulkers/IWstETH.sol
- contracts/bulkers/MainnetBulker.sol
- deployments/mainnet/weth/deploy.ts
- deployments/mainnet/weth/relations.ts
- deployments/mumbai/usdc/deploy.ts
- hardhat.config.ts
- scenario/BulkerScenario.ts
- scenario/MainnetBulkerScenario.ts
- test/bulker-test.ts
- test/helpers.ts
Creating a new Bulker that is able to wrap/unwrap `stETH`.
Includes the following changes:
- moves the Bulker into a `bulkers/` subdirectory, renaming it to `BaseBulker`
- creates a new `MainnetBulker` that inherits from `BaseBulker` and adds `supplyStEthTo` and `withdrawStEthTo` functions
- converts the bulker action constants to strings/bytes32 to decrease the likelihood that bulkers will create actions with conflicting values
- adds a `handleAction` function that contracts inheriting from `BaseBulker` can implement; by default it just reverts
- scenarios for wrapping and unwrapping via the `MainnetBulker`
TODO:
> Mainnet WETH Bulker

- plugins/scenario/World.ts
- plugins/scenario/utils/index.ts
- tasks/deployment_manager/task.ts
Add an impersonate flag for migration simulations so developers can test their new migration script.
> Impersonate flag for migrate task

- scripts/liquidation_bot/index.ts
- scripts/liquidation_bot/liquidateUnderwaterBorrowers.ts
- test/liquidation/liquidation-bot-script.ts
- test/liquidation/liquidation-bot-test.ts
- test/liquidation/makeLiquidatableProtocol.ts
Currently, the bot will only `BuyCollateral` if there are accounts to be absorbed. This change will make it so the bot will also look for `BuyCollateral` opportunities separately.
> Look for BuyCollateral opportunities even if no accounts are absorbable

- package.json
- scripts/liquidation_bot/index.ts
- scripts/liquidation_bot/liquidateUnderwaterBorrowers.ts
- test/liquidation/liquidation-bot-script.ts
- yarn.lock
Transactions can be sent to Flashbots by specifying `USE_FLASHBOTS=true` in env variables.
> Add Flashbots support to the liquidation bot

- scripts/liquidation_bot/index.ts
`useFlashbots` is undefined if you don't define a `USE_FLASHBOTS` environment variable; we should check for its existence before calling `.toLowerCase` on it (which will throw an error otherwise)
> check for useFlashbots before down-casing

- scripts/liquidation_bot/index.ts
- scripts/liquidation_bot/liquidateUnderwaterBorrowers.ts
- scripts/liquidation_bot/sendTransaction.ts
- test/liquidation/liquidation-bot-script.ts
This PR implements liquidating positions via the private mempool (to prevent front-running) by sending bundles to Flashbots. Both the Flashbots and non-Flashbots paths have been tested E2E on Goerli.
> Liquidate via Flashbots bundles

- .github/workflows/run-forge-tests.yaml
- contracts/liquidator/Liquidator.sol
- scenario/ConstraintScenario.ts
- scenario/LiquidationBotScenario.ts
- scripts/liquidation_bot/deploy.ts
- test/liquidation/liquidation-bot-test.ts
- test/liquidation/makeLiquidatableProtocol.ts
adds a `maxCollateralToPurchase` field to the Liquidator's pool config. This lets us specify a maximum amount of the given collateral asset to purchase, so that we don't try to purchase all the liquidity in a given pool, suffer a ton of slippage, and then fail to make a profit/pay back the flash loan.
Added a bunch of scenarios to flex this behavior. Scenarios have given us a general sense of the depth of the current Uniswap/SushiSwap pools that we're using; but of course, these things are subject to change as real-world conditions evolve.
> add maxCollateralToPurchase to Liquidator.sol

- contracts/IERC20NonStandard.sol
- contracts/bulkers/BaseBulker.sol
- contracts/bulkers/MainnetBulker.sol
- contracts/test/NonStandardFaucetToken.sol
- test/bulker-test.ts
This PR contains the following contract changes to `BaseBulker` and `MainnetBulker` based on OZ's recent audit:
- **L-05 Lack of return validation** - We added transfer success checks to these transfer calls.
- **L-09 Partial implementation of Ownable library** - We added a `transferAdmin` function to the `BaseBulker` contract. We will stick with a self-implementation of the Ownable logic to stay consistent with the rest of the contracts in the repo (like `Configurator`).
> Bulker contract updates for audit

- contracts/IERC20NonStandard.sol
- contracts/WstETHPriceFeed.sol
- contracts/bulkers/BaseBulker.sol
- contracts/bulkers/MainnetBulker.sol
- contracts/test/NonStandardFaucetToken.sol
- test/bulker-test.ts
This PR contains changes to the following (mostly stylistic) issues highlighted in OZ's audit:
- **L-04 Missing docstrings** - We added a comprehensive set of docstrings to the various constants and functions in the `BaseBulker` and `MainnetBulker` contracts.
- **L-06 Possible mismatch between native and wrapped tokens in different chains** - It is true that the `BaseBulker` is only intended to work for EVM chains with a native token and wrapped native token that implements the IWETH interface. We have documented this requirement more clearly.
- **L-07 sweepToken can potentially call a malicious token** - We expect the admin of the `Bulker` (the `Timelock`) to never sweep malicious tokens, but we added a cautionary note just in case. That being said, we think that a malicious token is …
> wstETHPriceFeed and BaseBulker stylistic changes

- contracts/Comet.sol
- contracts/CometCore.sol
- contracts/ConstantPriceFeed.sol
- contracts/IERC20NonStandard.sol
- contracts/IPriceFeed.sol
- contracts/ScalingPriceFeed.sol
- contracts/WstETHPriceFeed.sol
- contracts/bulkers/BaseBulker.sol
- contracts/bulkers/MainnetBulker.sol
- contracts/test/NonStandardFaucetToken.sol
- deployments/mainnet/weth/configuration.json
- deployments/mainnet/weth/deploy.ts
- plugins/deployment_manager/Cache.ts
- plugins/deployment_manager/Deploy.ts
- plugins/deployment_manager/Utils.ts
- scenario/SupplyScenario.ts
- scenario/utils/index.ts
- test/bulker-test.ts
- test/constant-price-feed-test.ts
- test/scaling-price-feed-test.ts
- test/wsteth-price-feed.ts
This PR implements and modifies price feeds to support the upcoming WETH deployment. The favored plan so far is to use ETH-denominated price feeds as opposed to USD price feeds, but stick with using 8 decimals for prices to avoid having to change the `Comet` and `Configurator` implementations. 
This would require: 
- A new wrapper price feed (`ScalingPriceFeed.sol`) that scales prices up or down to 8 decimals
- A new `ConstantPriceFeed` that always returns 1e8 for the `WETH` base asset, since should always hold a 1:1 value with ETH
- Modifications to the `WstETHPriceFeed` to return prices in terms of ETH instead of USD
This is an alternative approach to #626, which is a more complex change but could be a better long-term solution.
*Note: This PR also now contains the changes from #634 and …
> Price feeds for WETH deployment + Bulker changes for OZ audit

- deployments/fuji/usdc/configuration.json
- deployments/goerli/usdc/configuration.json
- deployments/kovan/usdc/configuration.json
- deployments/mainnet/usdc/configuration.json
- deployments/mainnet/weth/configuration.json
- deployments/mainnet/weth/deploy.ts
- deployments/mumbai/usdc/configuration.json
- plugins/deployment_manager/Cache.ts
- plugins/deployment_manager/DeploymentManager.ts
- plugins/scenario/utils/TokenSourcer.ts
- scenario/constraints/MigrationConstraint.ts
- scenario/constraints/ModernConstraint.ts
- scenario/constraints/UtilizationConstraint.ts
- src/deploy/Network.ts
- src/deploy/NetworkConfiguration.ts
- src/deploy/index.ts
* Add a fromDep to deployment manager which can be used for sharing dependency contracts from another deployment
* Always attempt to initialize storage if needed, and not necessarily as gov
* Always deploy an initial implementation contract instead of using the factory marker
* Only take gov admin actions if we own the cometAdmin
* Expose the primitives necessary for a proposal to configurate later, if/when admin cannot
* Add an env flag for migration constraint to skip non-migration scenarios
* Defer reading current config in modern constraint (bugfix)
> Refactor deploy to support second markets

- contracts/ConstantPriceFeed.sol
- contracts/IERC20NonStandard.sol
- contracts/ScalingPriceFeed.sol
- contracts/WstETHPriceFeed.sol
- contracts/bulkers/BaseBulker.sol
- test/bulker-test.ts
- test/constant-price-feed-test.ts
These are changes in response to the WETH deployment [audit](https://gist.github.com/andresbach/a01686b1ef8bdf51d46046f2cfc93307) conducted by OZ:
- **L01 - Lack of input validation** - We originally avoided zero address checks because there are a vast amount of accidental addresses that can be set here and checking for a specific one seems unnecessary. However, we have reconsidered that position after seeing the reasons for including a zero address check listed in this [post](https://forum.openzeppelin.com/t/removing-address-0x0-checks-from-openzeppelin-contracts/2222/13).
- **L02 - Improper implementation of Chainlink AggregatorV3Interface** - We updated the hard-coded return values for `roundId` and `answeredInRound` to be 1 to comply with the Chainlink specification.
- **L04 - …
> WETH deployment audit changes

- deployments/mainnet/weth/deploy.ts
- plugins/deployment_manager/DeploymentManager.ts
We need to spider the `USDC` deployment before calling `fromDep` on it so all the aliases are populated in the cache. Otherwise, `fromDep` may try to import an `undefined` contract. 
There are many approaches to this and this PR takes the simplest approach of spidering in the deploy script. Another approach could be to handle the spidering directly in `fromDep`.
> Spider USDC deployment before calling `fromDep`

- deployments/fuji/usdc/configuration.json
- deployments/goerli/usdc/configuration.json
- deployments/kovan/usdc/configuration.json
- deployments/mainnet/usdc/configuration.json
- deployments/mainnet/weth/configuration.json
- deployments/mumbai/usdc/configuration.json
- src/deploy/NetworkConfiguration.ts
This PR adds a new `ScientificNotation` string type to `NetworkConfiguration` that is required for certain fields (e.g. `supplyCap`, `baseMinForRewards`). The configuration parser will safely convert these values into bigints without losing precision; with one caveat, scientific notations that use decimals in the coefficient still run the risk of precision loss because those are converted directly to javascript numbers.
> Convert from scientific notation to bigint in configuration

- scripts/liquidation_bot/liquidateUnderwaterBorrowers.ts
- Fix spelling
- Increase severity of finding purchasable collateral to `ALERT`
Maybe `ALERT` is extreme; maybe `WARNING`?
> alert on purchasable collateral

- test/tracking-index-bounds-test.ts
Looks like `1e15` is a reasonable `trackingIndexScale` for the `WETH` deploy. We could consider `1e12` to increase the upper bound (less chance of overflow), but it's nice to keep the index scale the same as that of the `USDC` deploy.
A `baseMinForRewards` of `100e18` seems to be good enough, but I recommend `1000e18` just to be safe.
> Add unit tests to sanity check tracking index scale bounds for WETH

- test/bulker-test.ts
Opening this so we can close #545. #645 adds tests for the global tracking indices, and more user indices tests could be added separately, but the open PR doesn't address and there are still open XXXs to record
> Cleanup some old XXXes

- scenario/LiquidationBotScenario.ts
Liquidity for LINK has become a bit tighter; swapping 250,000 LINK currently results in >4% slippage (which makes liquidating unprofitable):
So we're starting to see LiquidationBot scenario failures:
Reducing the amount we attempt to liquidate in LiquidationBot scenarios.
> reduce LINK amounts in LiquidationBot scenarios

- deployments/goerli/weth/migrations/1675148548_set_up_ens_subdomain_and_text_record.ts
This tests the script in PR #671 on goerli.
Proposal was executed in this [transaction](https://goerli.etherscan.io/tx/0xc31d01dc8ac7c404f97c2aebfbea0b8dcfe9dd925f53b5f33b5d8b478a87661f).
The subdomain can be verified [here](https://app.ens.domains/name/v3-additional-grants.compound-community-licenses.eth/details) (make sure to connect to goerli).
> Set up ENS subdomain and text record on goerli

- deployments/mainnet/weth/migrations/1675148548_set_up_ens_subdomain_and_text_record.ts
A proposal for setting up the `v3-additional-grants.compound-community-licenses.eth` ENS subdomain and adding a text record for official Comet deployments.
> Migration script for setting up an ENS subdomain and text record

- deployments/polygon/usdc/configuration.json
- deployments/polygon/usdc/migrations/1675200105_raise_polygon_supply_caps.ts
This allows us to update a variety of configs (e.g. CF, supply caps) more easily.
> Set entire Comet configuration for Polygon proposal

- forge/test/PolygonLiquidator.t.sol
- plugins/deployment_manager/DeploymentManager.ts
- scenario/LiquidationBotScenario.ts
- scripts/liquidation_bot/deploy.ts
- scripts/liquidation_bot/liquidateUnderwaterBorrowers.ts
This PR does the following:
- adds Forge tests for Polygon liquidation
- updates scenarios to run for Polygon
- updates the Liquidation Bot deploy script.
The existing Liquidation contract works for Polygon. Using Uniswap, we are currently able to swap
- 500 WETH (~$750K)
- 30 WBTC (~$600K)
- 500,000 WMATIC (~$600K)
Swap liquidity is the limiting factor for the Liquidation Bot (how much of a given asset can you swap before the price slippage exceeds the discount that the protocol has sold the collateral for, making the swap unprofitable).
But there is an additional challenge for Polygon: flash loan liquidity.
When taking out a flash loan, we have to find a Uniswap pool where 1) one of the paired tokens is the base token of the protocol, and 2) the other token is not one of the collateral …
> Polygon liquidator updates

- deployments/polygon/usdc/configuration.json
removing `(Polygon)` from the contract name.
as reference, some other contracts incorporate `(PoS)` into their name, but there doesn't seem to be a solid convention around this.
USDC: `USD Coin (PoS)`
WBTC: `(PoS) Wrapped BTC`
WETH: `Wrapped Ether`
WMATIC: `Wrapped Matic`
> remove (Polygon) from name

- deployments/polygon/usdc/deploy.ts
Set the Polygon timelock delay to 1 day; make it possible to set it to as little as 12 hours in the future.
> update Polygon timelock delay

- deployments/polygon/usdc/configuration.json
This is so the rewards config can be set on deploy. The alternative is to set the reward config in the cross-chain proposal to initialize the Polygon market.
> Set rewards token address in Polygon configuration

- .github/workflows/enact-migration.yaml
- hardhat.config.ts
Currently, running `Enact` in CI using Seacrest will fail when multiple networks are used (e.g. for cross-chain governance proposals that read from Polygon and write to mainnet). This is because Seacrest's connection with WalletConnect is for a specific chain, so trying to access a different chain will result in a `could not detect network` error.
This change supports making multiple connections to Seacrest/WalletConnect, all from a single phone. We introduce optional `GOV_NETWORK` and `GOV_NETWORK_PROVIDER` env variables to override the provider for a specific chain when creating the HREs. The `Enact` CI job determines the `GOV_NETWORK` based on what the original selected network is.
> Support multiple connections to Seacrest in Enact

- scenario/LiquidationBotScenario.ts
- scenario/constraints/TokenBalanceConstraint.ts
- add the fix for issue that ⛑️ found (`deployment` keys that should be `network` keys)
- reduce `cbETH` swap amounts from 1000 to 750 (due to shrinking liquidity)
- add deployment-specific base token amounts, so that we don't try to source 3M WETH for the `mainnet-weth` deployment
> Fix Liquidation Bot scenarios

- contracts/CometRewards.sol
- test/rewards-test.ts
This PR introduces a `setRewardsClaimed` function that gives the admin the ability to set rewards claimed for any user. This gives us the ability to initialize a new reward distribution that doesn't necessarily have to retroactively reward all past usage of Comet. 
We would have to compute off-chain the amount that each user would be able to claim at a specific block number `x` and write it on-chain via the `setRewardsClaimed` function. This allows us to essentially set the start time of the rewards accrual to be after that specific block number `x`.
> Add ability to pre-populate rewards claimed for users in CometRewards

- scripts/liquidation_bot/index.ts
- scripts/liquidation_bot/liquidateUnderwaterBorrowers.ts
- test/liquidation/liquidation-bot-script.ts
- test/liquidation/makeLiquidatableProtocol.ts
After checking all addresses, the Liquidation Bot does a check for any purchasable collateral left in the protocol.
It checks the value of `baseReserves` against the value of `targetReserves` before checking for each asset.
`baseReserves` and `targetReserves` are both BigNumbers however, and they have their own comparison functions:
```
> BigNumber.from("10") > BigNumber.from("5")
false
> BigNumber.from("10").gt(BigNumber.from("5"))
true
```
Converting those values to BigInts first should get us the comparisons we expect.
> `hasPurchasableCollateral` fixes for liquidation bot

- scenario/BulkerScenario.ts
The Bulker scenario for the WETH market will fail whenever the supply cap is hit. This change ensures there is always ample supply cap before running the scenario.
> Bump supply cap in Bulker scenario

- scripts/liquidation_bot/liquidateUnderwaterBorrowers.ts
The Polygon Liquidation Bot was failing because we do not define a liquidation threshold (the smallest value that the Liquidation Bot will attempt to buy/sell) for Polygon/USDC.
~~Also, increasing the mainnet/USDC liquidation threshold so we get fewer liquidation attempts where the Bot will spend $90 in gas to earn $40.~~ Bumping USDC involves updating some tests, unexpectedly. Going to keep this change simple and just fix the Polygon issue for now.
> add Polygon liquidation threshold

- scripts/liquidation_bot/liquidateUnderwaterBorrowers.ts
Currently, the protocol has a small amount of WETH for sale: 700000385672350.
The price from ChainLink for WETH is around 141226378000.
The bot calculates the price as `collateralReserves * price / assetScale`:
```
700000385672350 * 141226378000 / 1e18 = 98_858_519
``` 
So the price value we're using here is $98 USDC. That's off by two decimal places, it's actually ~$0.98:
So the bot thinks there is $98 of WETH for sale; it attempts to buy this purchasable collateral (passing in the 10e6 liquidation threshold as an argument). The contract receives the request, sees that there is less than 10e6 worth of collateral for sale, and emits an `AbsorbWithoutBuyingCollateral` event. The bot just spent $7 in gas, and nothing is changed.
I think this changed with the updates we made for the WETH …
> fix hasPurchasableCollateral price calculation

- contracts/CometRewards.sol
- scenario/RewardsScenario.ts
- test/helpers.ts
- test/rewards-test.ts
This allows us to scale the Comet accrued tracking balances by varying amounts for different reward tokens.
> CometRewards with multiplier

- deployments/goerli/usdc/migrations/1681942579_upgrade_governor_bravo.ts
- tasks/deployment_manager/task.ts
This governor upgrade was made on mainnet last year in [proposal 115](https://compound.finance/governance/proposals/115), but never made to Goerli.
Migration job: https://github.com/compound-finance/comet/actions/runs/4758731465/jobs/8457147538
On-chain proposal: https://compound.finance/governance/proposals/73?target_network=goerli
> Proposal to upgrade Goerli governor to allow sending ETH from the Timelock

- .github/workflows/deploy-market.yaml
- hardhat.config.ts
- package.json
- plugins/deployment_manager/DeploymentManager.ts
- plugins/deployment_manager/ManualVerify.ts
- plugins/deployment_manager/Verify.ts
- plugins/deployment_manager/test/DeploymentManagerTest.ts
- plugins/deployment_manager/test/VerifyTest.ts
- tasks/deployment_manager/task.ts
- yarn.lock
This PR improves the deploy step by allowing us to recover the `VerifyArgs` if a deploy job fails mid-deploy. This allows us to easily resume verification of contracts that were deployed but not yet verified. We also upgrade `hardhat-etherscan` to support verifying contracts on L2s.
The changes in this PR are extracted from #728, which currently lives on the Optimism branch. I'm moving them to main since these are generic quality of life improvements that should be used on other branches as well, such as the Arbitrum one.
> QoL improvement for verifying contracts when deploying

- contracts/bridges/SweepableBridgeReceiver.sol
- contracts/bridges/arbitrum/ArbitrumBridgeReceiver.sol
- contracts/bridges/test/SweepableBridgeReceiverHarness.sol
- test/bridges/base-bridge-receiver-test.ts
- test/bridges/sweepable-bridge-receiver-test.ts
This PR adds native token and ERC20 sweeping functions to the Arbitrum bridge receiver per OpenZeppelin's recommendations.
Changes include:
- a `SweepableBridgeReceiver` contract, which exposes `sweepToken` and `sweepNativeToken` functions that can be called by the localTimelock (adapted from the Bulker contract
- ~~a`BridgeReceiverCore` contract that is shared by `BaseBridgeReceiver` and `SweepableBridgeReceiver` (to allow both to use the `localTimelock` variable and the `Unauthorized` custom error)~~
- unit tests, including a SweepableBridgeReceiver harness contract
> Add token sweeping functions to Arbitrum Bridge Receiver

- scenario/InterestRateScenario.ts
Someone supplied 100bn USDC to the Goerli USDC market, which caused 2 scenarios using the utilization constraint to fail because it became impossible to achieve a target utilization with so much supply in the market. This PR skips those 2 scenarios.
Another solution is to enhance the utilization constraint such that it can also withdraw base supplied by whales to achieve the target utilization.
> Skip utilization scenarios for Goerli USDC

- contracts/pricefeeds/ConstantPriceFeed.sol
- contracts/pricefeeds/ScalingPriceFeed.sol
- contracts/pricefeeds/WBTCPriceFeed.sol
- contracts/pricefeeds/WstETHPriceFeed.sol
- test/wbtc-price-feed.ts
This PR creates a custom price feed for WBTC / USD by reading from both the WBTC / BTC and BTC / USD price feeds. This will allow the cUSDCv3 market to get a more accurate price for WBTC.
We also organize the contracts repo by moving all the custom price feed contracts into a separate `pricefeeds` subdirectory.
> Create custom price feed for WBTC

- scripts/liquidation_bot/index.ts
- scripts/liquidation_bot/liquidateUnderwaterBorrowers.ts
In #748, we updated the Comet instance used in the liquidation bot to attach the signer before being passed around as an argument.
https://github.com/compound-finance/comet/pull/748/files#diff-985edbf80fe4c689f86ad3dcd779b4effe7ead300ec1f6dd5068f7b8d47e41eeR90
This approach doesn't work when `USE_FLASHBOTS` is set to `true`. In that case, we set the signer to be an Ethers Wallet, which has the side-effect of removing the Provider from the Comet instance. Subsequent attempts to read values via the provider fail.
> Do not attach signer to comet instance

- .github/workflows/run-semgrep.yaml
This Semgrep workflow runs 2 rule sets over all the pull requests.
The rule sets include both generic Solidity security detections and the comet-specific ones.
We've reviewed the comet repository issues, pull requests and commits and created a few rules according to the fixes that were proposed by OZ/ChainSecurity/Certora and have been accepted by Compound.
Most of the issues have been closed without fixes, and some of others are unfeasible to detect with Semgrep.
You can see it in action here: https://github.com/Decurity/comet/pull/2
Right now if you run these rules over the whole comet codebase, the stats is as follows:
Ran 9 rules on 36 files: 32 findings.
23 of these are missing sanity checks on constructor arguments (each argument = 1 finding). Of course many of them might not …
> Adding the Semgrep worflow by Decurity

- contracts/Comet.sol
My team [received a grant](https://questbook.app/dashboard/?grantId=0xeb047900b28a9f90f3c0e65768b23e7542a65163&isRenderingProposalBody=true&proposalId=0x21b&chainId=10) from [CGP 2.0](https://docs.google.com/document/d/1PYYFazs9XxcidJn0Q0zl-XZEHWTaWZh_KX72Ym6qS0Y/edit) to add [Flexible Voting](https://github.com/ScopeLift/flexible-voting/) support to Compound V3. 
In order to implement our extension we need to be able to determine, for any given block:
1. how much principal a given account has supplied up to that time, and
1. how much total principal has been supplied to Comet up to that time
Our belief is that the easiest way to do this involves overriding the `Comet.updateBasePrincipal` function to store a couple checkpoints. You can see the PR for this work in …
> Make updateBasePrincipal virtual to facilitate Comet extension

- .prettierignore
- .prettierrc.json
The Comet repo currently has rules set up for both Prettier and ESLint, even though we only enforce the rules for ESLint. The move from Prettier to ESLint was decided in https://github.com/compound-finance/comet/pull/321. 
Keeping the Prettier configs in the repo while not enforcing them is arguably worse than just not having the configs in the first place, since contributors may end up running the Prettier (e.g. via VSCode auto-format) for some files and introduce very large diffs. Removing Prettier should help reduce the formatting diffs introduced by contributors.
> Remove Prettier

- contracts/bridges/optimism/OptimismBridgeReceiver.sol
This change should extend the `OptimismBridgeReceiver` with some functionality to sweep ERC20 and native tokens.
> Make OptimismBridgeReceiver sweepable

- deployments/linea-goerli/usdc/configuration.json
- deployments/linea-goerli/usdc/migrations/1687878801_increase-supply-caps.ts
The Linea quest is having issues right now because we reach the supply limits, I created this migration script to increase them.
> feat: increase supply caps for ETH and WBTC for the linea quest

- plugins/scenario/utils/hreForBase.ts
- scenario/MainnetBulkerScenario.ts
- scenario/WithdrawReservesScenario.ts
- scenario/constraints/Requirements.ts
- scenario/constraints/ReservesConstraint.ts
- scenario/constraints/index.ts
- scenario/context/CometContext.ts
- scenario/utils/index.ts
- scripts/clone-multisig.ts
- scripts/liquidation_bot/liquidateUnderwaterBorrowers.ts
Attempting to fix as many of the currently-failing scenarios as possible.
The only errors that should remain after this PR are the Base deployments' inability to source cbETH.
> Fix failing scenarios

- .github/workflows/deploy-market.yaml
- .github/workflows/enact-migration.yaml
- .github/workflows/prepare-migration.yaml
Per: https://github.com/hayesgm/seacrest/releases/tag/v2
This PR will update /comet git actions to use the latest version of seacrest. 
So can unblock from failing seacrest@v1 due to WalletConnect's breaking changes.
Test run: https://github.com/compound-finance/comet/actions/runs/5548176565
> Upgrade git action to use new seacrest

- deployments/goerli/usdc/relations.ts
Linea Goerli's `MessageService` contract just upgraded its implementation to an unverified contract, causing all testnet scenarios to fail when spidering Goerli. This should fix that.
> Fix unverified Linea contract issue

- .github/workflows/enact-migration.yaml
- .github/workflows/prepare-migration.yaml
- deployments/arbitrum-goerli/usdc/configuration.json
- deployments/arbitrum-goerli/usdc/migrations/1689112067_configurate_and_ens.ts
- deployments/arbitrum-goerli/usdc/roots.json
- deployments/goerli/usdc/relations.ts
- deployments/goerli/usdc/roots.json
- scripts/CCTP-attestation.ts
Migration for the Arbitrum goerli native usdc market to initialize supply cap of the markets. 
- Set Comet factory in the Configurator
- Initialize supply cap of each assets
- Set reward speed of usdc.e market to 0
- Seeding reserve usdc via CCTP to native usdc comet
> Migrate Arbitrum Goerli Native usdc

- contracts/pricefeeds/MultiplicativePriceFeed.sol
- test/pricefeeds/constant-price-feed-test.ts
- test/pricefeeds/multiplicative-price-feed.ts
- test/pricefeeds/scaling-price-feed-test.ts
- test/pricefeeds/wbtc-price-feed.ts
- test/pricefeeds/wsteth-price-feed.ts
This generalizes the logic used in the recently audited [`WBTCPriceFeed`](https://github.com/compound-finance/comet/pull/737) to create a `MultiplicativePriceFeed` that derives its price from multiplying the prices from two other price feeds together. 
This is a flexible wrapper price feed that can be used to generate prices for any asset that does not have a price feed that fits Comet's expected price denomination. e.g. if we wanted to add `cbETH` to `cUSDCv3`, there is no Chainlink price feed for `cbETH / USD`, so we would need to multiply the `cbETH / ETH` and `ETH / USD` price feeds together to get `cbETH / USD`
> Multiplicative Price Feed

- scenario/LiquidationBotScenario.ts
These scenarios are noisy and don't really give us anything actionable to do at this point. Monitoring on-chain liquidity should be done outside of scenarios.
> Skip liquidation bot scenarios
