- contracts/liquidator/Liquidator.sol
- test/liquidation/liquidation-bot-test.ts
- test/liquidation/makeLiquidatableProtocol.ts
adding a few events to the Liquidator contract.
open to suggestions for other events.
> Liquidator events

- docs/README.md
Updated explanations/formula for supply/borrow indices and added an explanation for `principal` value.
> Update `Collateral and Borrowing` section of docs

- contracts/liquidator/Liquidator.sol
Tiny clean up, no need for this XXX comment
> Delete comment which is not needed

- src/deploy/Development.ts
- src/deploy/Network.ts
This PR removes the need to use a `fastGovernanceExecute` (propose and execute changes via governance; only doable on testnets) in our deploy scripts, which makes them more compatible for mainnet deploys.
> Remove the use of fastGovernanceExecute in our deploys

- deployments/hardhat/dai/deploy.ts
- scenario/RewardsScenario.ts
- scenario/context/CometContext.ts
This PRs adds scenarios for testing the CometRewards contract on each of our deployments.
> CometRewards scenarios

- contracts/CometProxyAdmin.sol
- contracts/Configurator.sol
- scenario/GovernanceScenario.ts
- scenario/context/CometContext.ts
- test/configurator-test.ts
This PR pulls out and isolates the contract changes introduced in Jared's refactoring PR #515. I've added unit tests and scenarios to test the new code paths.
> Improvements to CometProxyAdmin and Configurator

- scenario/RewardsScenario.ts
- scenario/constraints/ProposalConstraint.ts
- Fix occasional rewards test fail 
- Enable proposal constraint for all testnets
> Fix test, enable proposal constraint for all networks

- scripts/liquidation_bot/deploy.ts
- scripts/liquidation_bot/liquidateUnderwaterBorrowers.ts
```
RECIPIENT=0xabc DEPLOYMENT=usdc yarn hardhat run scripts/liquidation_bot/deploy.ts --network kovan
```
Newly-deployed liquidator.sol:
https://kovan.etherscan.io/address/0xB72dA9264D2621AAa98c5674857f8b596158B2E4#code
> Liquidation Bot deploy script

- scenario/BulkerScenario.ts
- scenario/RewardsScenario.ts
- scenario/context/CometActor.ts
- scenario/context/CometContext.ts
- scenario/utils.ts
This PR adds scenarios for Bulker.
> Bulker scenarios

- deployments/mainnet/usdc/migrations/1661899622_rewards.ts
- deployments/mainnet/usdc/roots.json
- deployments/relations.ts
- plugins/deployment_manager/Migration.ts
- plugins/deployment_manager/index.ts
- scenario/BulkerScenario.ts
- scenario/RewardsScenario.ts
- scenario/constraints/MigrationConstraint.ts
- scenario/constraints/ProposalConstraint.ts
- scenario/constraints/index.ts
- scenario/context/CometContext.ts
- scenario/utils.ts
~~We would want to adjust the actual COMP speed to equal the sum of the streams we are replacing (TODO).~~
This has been adjusted, now need to finish testing
> Potential rewards proposal

- package.json
- scenario/AllowScenario.ts
- scenario/ApproveThisScenario.ts
- scenario/BulkerScenario.ts
- scenario/CometScenario.ts
- scenario/ConfiguratorScenario.ts
- scenario/GovernanceScenario.ts
- scenario/InterestRateScenario.ts
- scenario/PauseGuardianScenario.ts
- scenario/RewardsScenario.ts
- scenario/SupplyScenario.ts
- scenario/TransferScenario.ts
- scenario/WithdrawScenario.ts
- scenario/constraints/CometBalanceConstraint.ts
- scenario/constraints/FilterConstraint.ts
- scenario/constraints/Fuzzing.ts
- scenario/constraints/MigrationConstraint.ts
- scenario/constraints/ModernConstraint.ts
- scenario/constraints/PauseConstraint.ts
- scenario/constraints/ProposalConstraint.ts
- scenario/constraints/Requirements.ts
- scenario/constraints/TokenBalanceConstraint.ts
- scenario/constraints/UtilizationConstraint.ts
- scenario/context/Address.ts
- scenario/context/CometAsset.ts
- scenario/context/CometContext.ts
- scenario/context/Gov.ts
- scenario/utils.ts
turns out we haven't been linting the scenario directory
> lint `./scenario`

- .eslintrc.js
- package.json
- plugins/scenario/worker/Parent.ts
- scenario/AllowBySigScenario.ts
- scenario/ApproveThisScenario.ts
- scenario/ConfiguratorScenario.ts
- scenario/LiquidationScenario.ts
- scenario/PauseGuardianScenario.ts
- scenario/SupplyScenario.ts
- scenario/TransferScenario.ts
- scenario/WithdrawReservesScenario.ts
- scenario/WithdrawScenario.ts
- scenario/utils/index.ts
- yarn.lock
Uses a new cut of hardhat with selectors included in error messages.
~~XXX: currently 3 new test failures due to "incorrect parameters"...~~
Added a second patch to hardhat to fix inferring errors...
> Attempt to patch around custom errors in hardhat

- deployments/fuji/usdc/migrations/1665028496_absorb_transfer_event_and_auto_collateral.ts
- hardhat.config.ts
- scripts/liquidation_bot/deploy.ts
- scripts/vote-queue-execute.ts
May need some tweaks (still running now, fuji voting period is loong ⏳ )
> Add a script to help testnet gov and improve interface for scripts

- tasks/deployment_manager/task.ts
This is useful for verifying contracts deployed e.g. from `prepare` that didn't get verified (like the CometFactory on a Comet upgrade), although we should probably change the prepare task to change the verification strategy, its still useful to have this option
> Add a publish task

- deployments/mainnet/weth/configuration.json
https://hackmd.io/wncIvkFTReWUe2AMMK2ezA?view
> Update the collateral params based on Gauntlet recommendations

- deployments/mainnet/weth/migrations/1666906928_raise_supply_caps_and_seed_reserves_and_rewards.ts
https://hackmd.io/wncIvkFTReWUe2AMMK2ezA?view
> Update the supply caps based on Gauntlet recommendations

- deployments/mainnet/usdc/migrations/1669668117_raise_weth_supply_cap.ts
- deployments/mainnet/usdc/migrations/1669668117_raise_weth_supply_cap_and_comp_lf.ts
Some risk parameter tweaks for cUSDCv3.
TODO:
> Proposal to bump WETH supply cap [cUSDCv3]

- deployments/goerli/usdc/migrations/1663870047_add_link.ts
- scenario/SupplyScenario.ts
- scenario/WithdrawScenario.ts
- scenario/constraints/ProposalConstraint.ts
This adds a new migration script for adding LINK as a collateral asset to Goerli.
> Proposal to add LINK to Goerli

- scenario/context/CometContext.ts
Noticed this due to a nonce issue in interest rate scens which were exercising utilization constraints, which were quietly failing to source collateral due to truncated supply caps.
> When bumping supply caps, bumps at least to min to avoid setting 0

- deployments/hardhat/dai/deploy.ts
- plugins/scenario/worker/Report.ts
- scenario/LiquidationBotScenario.ts
- scenario/TransferScenario.ts
- scenario/constraints/UtilizationConstraint.ts
- scenario/context/CometAsset.ts
- scenario/context/CometContext.ts
- src/deploy/index.ts
This can lead to multiple constraints violating each other, which is causing scen failures. Not sure when/why we needed this but we should find another way if sourcing without it is not enough.
> Do not source from actors

- deployments/mainnet/usdc/migrations/1670434836_v2_maintenance_1.ts
> Maintenance proposal for v2 reserves

- deployments/goerli/weth/configuration.json
- deployments/goerli/weth/migrations/1672860425_initialize_market.ts
Enact run: https://github.com/compound-finance/comet/actions/runs/3849939037/jobs/6559516200
Proposal executed: https://goerli.etherscan.io/tx/0xc7e1755a28378570de1c07b69736ec57e4da69da22f0a9e8cf692fddb551c043
> Proposal to enable cWETHv3 market on Goerli

- diagrams/l2_configurator_diagram.uml
> L2 Configurator Diagram

- plugins/deployment_manager/DeploymentManager.ts
Incorporates #651 based on the deployment branch instead of the proposal
> Fix fromDep to spider the dependency and load the contract from it

- scenario/LiquidationBotScenario.ts
need to ensure that the protocol is selling collateral in the LiquidationBotScenarios
> bump target reserves

- scripts/liquidation_bot/index.ts
> OnChainLiquidator, not Liquidator

- contracts/bulkers/BaseBulker.sol
- contracts/bulkers/MainnetBulker.sol
- scenario/MainnetBulkerScenario.ts
- scenario/constraints/Requirements.ts
- test/bulker-test.ts
Working with ⛑️ on updates to the Bulker and Webb3 to allow a user to wrap/unwrap ETH and stETH.
related Webb3 changes: https://github.com/compound-finance/webb3/pull/265
> Bulker updates for wrapping/unwrapping native token as base asset and supplying stETH amount

- deployments/polygon/usdc/configuration.json
- deployments/polygon/usdc/deploy.ts
- scenario/BulkerScenario.ts
Updating the Polygon config to reflect our current proposed set of assets: USDC as base, with WMATIC, WETH and WBTC as collateral assets.
All configuration variables (collateral factor, liquidation factor, etc) are placeholder, pending guidance from Gauntlet
> Polygon collateral assets

- scenario/V2Scenario.ts
This change isn't specific to the DSR branch, but running against that migration looks like there might be some issues redeeming after minting to look into...
> Some basic v2 scenarios

- scenario/constraints/NativeTokenConstraint.ts
- src/deploy/index.ts
Updates to NativeTokenConstraint to work with Polygon deploy
> update NativeTokenConstraint; add Polygon whales

- deployments/mainnet/weth/migrations/1674835242_bump_supply_caps.ts
> A proposal to bump the cbETH supply cap

- deployments/polygon/usdc/migrations/1675200105_raise_polygon_supply_caps.ts
- scenario/utils/index.ts
- scenario/utils/relayMessage.ts
- scenario/utils/relayPolygonMessage.ts
This PR adds ERC20 bridging actions to the proposal for bridging USDC reserves and COMP rewards. I also added support for relaying Polygon token bridging events to our scenarios.
> Bridge USDC reserves and COMP rewards to Polygon Comet

- scenario/GovernanceScenario.ts
- scenario/LiquidationBotScenario.ts
- scenario/RewardsScenario.ts
- scenario/constraints/MigrationConstraint.ts
Issues fixed:
- The proposer not having enough gas to propose
- Some state synced events not being recognized while bridging
- Getting the reward token when it is not a collateral asset
- Liquidation bot scenarios failing due to high WBTC slippage
> Fix Polygon scenarios

- scripts/seed-fork-state-example.ts
- scripts/seed-fork-state.ts
This is an example script that can be used to seed a fork with some initial state relevant for testing Comet.
> Example script for seeding state on a fork

- src/deploy/NetworkConfiguration.ts
- src/deploy/index.ts
> Fix typescript errors

- plugins/deployment_manager/test/CacheTest.ts
- plugins/deployment_manager/test/MigrationTest.ts
- plugins/scenario/index.ts
- scenario/ApproveThisScenario.ts
- scenario/BulkerScenario.ts
- scenario/ConfiguratorScenario.ts
- scenario/MainnetBulkerScenario.ts
- scenario/SupplyScenario.ts
- scenario/TransferScenario.ts
- scenario/WithdrawScenario.ts
- scenario/constraints/CometBalanceConstraint.ts
- scenario/constraints/Fuzzing.ts
- scenario/constraints/MigrationConstraint.ts
- scenario/constraints/ModernConstraint.ts
- scenario/constraints/NativeTokenConstraint.ts
- scenario/constraints/ProposalConstraint.ts
- scenario/constraints/SupplyCapConstraint.ts
- scenario/constraints/TokenBalanceConstraint.ts
- scenario/constraints/UtilizationConstraint.ts
- scenario/context/CometAsset.ts
- scenario/context/CometContext.ts
- scenario/context/Gov.ts
- scenario/utils/bridgeProposal.ts
- scenario/utils/index.ts
- scenario/utils/relayPolygonMessage.ts
- tsconfig.json
This fixes some more type inconsistencies that Typescript was complaining about throughout the scenario codebase.
> Fix more typescript type inconsistencies

- .github/workflows/run-coverage.yaml
This fixes our coverage CI job by turning on the optimizer when compiling contracts.
> Fix coverage

- .github/workflows/deploy-market.yaml
- .github/workflows/enact-migration.yaml
- .github/workflows/prepare-migration.yaml
- .github/workflows/run-contract-linter.yaml
- .github/workflows/run-coverage.yaml
- .github/workflows/run-eslint.yaml
- .github/workflows/run-forge-tests.yaml
- .github/workflows/run-gas-profiler.yaml
- .github/workflows/run-scenarios.yaml
- .github/workflows/run-unit-tests.yaml
- deployments/optimism-goerli/usdc/relations.ts
- deployments/optimism/usdc/relations.ts
- hardhat.config.ts
- plugins/import/etherscan.ts
- scenario/BulkerScenario.ts
- scenario/SupplyScenario.ts
- scenario/context/CometContext.ts
- scenario/utils/index.ts
- scenario/utils/relayOptimismMessage.ts
- src/deploy/index.ts
~~This PR refactors the cross-chain governance scenarios so that a single scenario can be used for all L2s/sidechains. We also move cross-chain governance scenarios into their own file.~~
This PR fixes a lot of different errors that are cropping up for Optimism scenarios.
> Fix Optimism scenarios

- plugins/deployment_manager/MigrationTemplate.ts
- plugins/deployment_manager/test/MigrationTemplateTest.ts
Updating migration template to include `govDeploymentManager`
> Update migration template

- package.json
- plugins/deployment_manager/DiffState.ts
- plugins/deployment_manager/Migration.ts
- plugins/deployment_manager/index.ts
- scenario/constraints/MigrationConstraint.ts
- scenario/constraints/ProposalConstraint.ts
- scenario/constraints/index.ts
- scenario/context/CometContext.ts
- yarn.lock
This adds a diff checker to check for state changes after a migration is run. This allows us to more comprehensively check for state changes because, right now, our migration verification logic will not catch any unintentional state changes. For example, in a proposal that only touches collateral factors, we'll check that `collateralFactor == some new amount`, but not that `liquidationFactor == old amount`. We could also potentially generate a report of all the state changes for easier viewing.
In order to isolate the state changes of each migration, we get rid of the `VerifyMigrationConstraint` and move the verify checks directly into the `ProposalConstraint` so that verification is called right after a proposal is executed. This way, we can verify the state changes of a specific …
> Diff checker for state changes after running a migration

- README.md
Update Spider section in README.
> Update Spider README

- contracts/CometRewards.sol
- test/rewards-test.ts
This adds an event for a function that modifies storage.
> Emit event when rewards claimed is set by the admin

- contracts/IGovernorBravo.sol
- deployments/arbitrum-goerli/usdc/configuration.json
- deployments/arbitrum-goerli/usdc/deploy.ts
- deployments/arbitrum-goerli/usdc/migrations/1679518383_configurate_and_ens.ts
- deployments/goerli/usdc/relations.ts
- src/deploy/index.ts
> Arbitrum testnet proposal

- deployments/polygon/usdc/migrations/1681313581_more_comp.ts
- hardhat.config.ts
- scenario/utils/isBridgeProposal.ts
> Proposal to transfer more COMP to Polygon

- deployments/polygon/usdc/migrations/1689168483_add_maticx_collateral.ts
- hardhat.config.ts
- scenario/AddMaticxCollateralScenario.ts
This PR contains migration script to add maticx as collateral in polygon usdc market.
> Add MATICx as collateral against polygon usdc

- .github/workflows/run-scenarios.yaml
- deployments/polygon/usdc/migrations/1689168483_add_maticx_collateral.ts
- scenario/AddMaticxCollateralScenario.ts
- removed permissions from `run-scenarios.yaml`
- minor refactoring
> Maticx refactor
